version: 2
jobs:
  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: dotnet build ./amqp-sidecar-tests/amqp-sidecar-tests.csproj
      - run: dotnet test ./amqp-sidecar-tests/amqp-sidecar-tests.csproj
  build:
    requires:
      - test
    docker:
      - image: docker:18.06.0-ce
    steps:
      - checkout
      # - setup_remote_docker:
      #     version: 18.06.0-ce
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t brbarnett/amqp-sidecar:ci -f ./amqp-sidecar/Dockerfile .
      - run: docker push -t brbarnett/amqp-sidecar:ci